mlpack: mlpack::ann::SoftsignFunction Class Reference
mlpack::ann::SoftsignFunction Class Reference
The softsign function, defined by.
Static Public Member Functions
static double deriv (const double y)
Computes the first derivative of the softsign function.
template<typename InputVecType , typename OutputVecType >
static void deriv (const InputVecType &y, OutputVecType &x)
Computes the first derivatives of the softsign function.
static double fn (const double x)
Computes the softsign function.
template<typename InputVecType , typename OutputVecType >
static void fn (const InputVecType &x, OutputVecType &y)
Computes the softsign function.
static double inv (const double y)
Computes the inverse of the softsign function.
template<typename InputVecType , typename OutputVecType >
static void inv (const InputVecType &y, OutputVecType &x)
Computes the inverse of the softsign function.
Detailed Description
The softsign function, defined by.
Definition at line 47 of file softsign_function.hpp.
Member Function Documentation
static double mlpack::ann::SoftsignFunction::deriv (const double y) inline static
Computes the first derivative of the softsign function.
Parameters
y Input data.
Returns
f'(x)
Definition at line 84 of file softsign_function.hpp.
template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftsignFunction::deriv (const InputVecType & y, OutputVecType & x) inline static
Computes the first derivatives of the softsign function.
Parameters
y Input activations.
x The resulting derivatives.
Definition at line 96 of file softsign_function.hpp.
static double mlpack::ann::SoftsignFunction::fn (const double x) inline static
Computes the softsign function.
Parameters
x Input data.
Returns
f(x).
Definition at line 56 of file softsign_function.hpp.
Referenced by fn().
template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftsignFunction::fn (const InputVecType & x, OutputVecType & y) inline static
Computes the softsign function.
Parameters
x Input data.
y The resulting output activation.
Definition at line 70 of file softsign_function.hpp.
References fn().
static double mlpack::ann::SoftsignFunction::inv (const double y) inline static
Computes the inverse of the softsign function.
Parameters
y Input data.
Returns
f^{-1}(y)
Definition at line 107 of file softsign_function.hpp.
Referenced by inv().
template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftsignFunction::inv (const InputVecType & y, OutputVecType & x) inline static
Computes the inverse of the softsign function.
Parameters
y Input data.
x The resulting inverse of the input data.
Definition at line 122 of file softsign_function.hpp.
References inv().
The documentation for this class was generated from the following file:
src/mlpack/methods/ann/activation_functions/softsign_function.hpp